### ISSUE TITLE
Can not pass the Mock object on argument of another service.

### ISSUE THREAD

**Issue by loic425** [pestphp/pest-plugin-mock#4]
With the \Mockery\MockInterface, you can pass the mock on argument of a service.

Example: 
```php
it('attaches creators', function (Book $book) {
    $request = Mockery::mock(Request::class);
    $kernel = Mockery::mock( KernelInterface::class);
    $user = Mockery::mock(UserInterface::class);

    $request->allows()->getMethod()->andReturns(Request::METHOD_POST);
    $this->security->allows()->getUser()->andReturns($user);

    $this->subscriber->attachCreator(new ViewEvent(
        $kernel,
        $request,
        HttpKernelInterface::MASTER_REQUEST,
        $book
    ));

    expect($book->getCreatedBy())->toBeInstanceOf(UserInterface::class);
})->with([
    new Book(),
]);
````

Not working example: 
```php
it('attaches creators', function (Book $book) {
    $request = mock(Request::class);
    $kernel = mock( KernelInterface::class);
    $user = mock(UserInterface::class);

    $request->allows()->getMethod()->andReturns(Request::METHOD_POST);
    $this->security->allows()->getUser()->andReturns($user);

    $this->subscriber->attachCreator(new ViewEvent(
        $kernel,
        $request,
        HttpKernelInterface::MASTER_REQUEST,
        $book
    ));

    expect($book->getCreatedBy())->toBeInstanceOf(UserInterface::class);
})->with([
    new Book(),
]);
```

**Comment by loic425** [comment]
@nunomaduro I think it could be solved by adding a getMock() method to have access to the Prophecy mock.

**Comment by nunomaduro** [comment]
@loic425 Methods calls are already proxy to the original mock object: https://github.com/pestphp/pest-plugin-mock/blob/abbcecff246e510a69735de261a4e25e47e70df0/src/Mock.php#L67.

**Comment by loic425** [comment]
> @loic425 Methods calls are already proxy to the original mock object:
> 
> https://github.com/pestphp/pest-plugin-mock/blob/abbcecff246e510a69735de261a4e25e47e70df0/src/Mock.php#L67
> .

Yes its methods are proxied, but you can't access to the mock object.
Look at my example. 
On Symfony, ViewEvent is not mockable cause it is final, so you have to instantiate it directly and you can't do it with the Pest mocks.

**Comment by loic425** [comment]
@nunomaduro 
I added this repository so you can figure it out
https://github.com/loic425/test-pestphp

**Comment by nunomaduro** [comment]
You mean this line? `$security = Mockery::mock(Security::class);`.

If yes, you can just do `$security = mock(Security::class)->allows()...`.
